import 'fake-indexeddb/auto';
import { afterEach, beforeEach, describe, expect, test } from 'vitest';

import type {
  HistoricalLegendAppPlayer,
  HistoricalLegendsAppPayload,
} from '../../data/historicalLegendsAppData';
import {
  importHistoricalLegendsPayload,
  parseHistoricalLegendsPayloadBytes,
  validateHistoricalLegendsPayload,
} from '../historicalLegendsImport';
import {
  __resetLeagueBuilderDatabaseForTests,
  clearAllLeagueBuilderData,
  createEmptyTeamRoster,
  getAllPlayers,
  getTeamRoster,
  savePlayer,
  saveTeamRoster,
  type Player,
} from '../leagueBuilderStorage';

const SOURCE_SHA = 'a'.repeat(64);

async function digest(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const result = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(result), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

function card(
  profileType: HistoricalLegendAppPlayer['historicalProfileType'],
  suffix: 'career' | 'peak' | 'draft',
): HistoricalLegendAppPlayer {
  const playerId = 'aaroh101';
  const identity = `historical:${playerId}`;
  return {
    id: `hl:${playerId}:${suffix}`,
    firstName: 'Hank',
    lastName: 'Aaron',
    gender: 'M',
    age: profileType === 'Peak' ? 29 : 31,
    bats: 'R',
    throws: 'R',
    primaryPosition: 'RF',
    power: 92,
    contact: 90,
    speed: 72,
    fielding: 76,
    arm: 82,
    velocity: 0,
    junk: 0,
    accuracy: 0,
    arsenal: [],
    overallGrade: 'A+',
    trait1: 'Clutch',
    personality: 'Competitive',
    chemistry: 'Competitive',
    morale: 75,
    mojo: 'Normal',
    fame: 0,
    salary: 100_000,
    leagueAssignments: [],
    ratingRevealState: 'revealed',
    createdDate: '2026-07-14T00:00:00.000Z',
    lastModified: '2026-07-14T00:00:00.000Z',
    isCustom: false,
    sourceDatabase: 'HISTORICAL_LEGENDS',
    sourceId: identity,
    historicalSourceId: identity,
    versionGroupId: identity,
    historicalProfileType: profileType,
    historicalLegend: {
      playerId,
      displayName: 'Hank Aaron',
      profileType,
      sourceCardId: `source:${suffix}`,
      sourceWindowId: suffix,
      sourceVersionClass: suffix,
      imageAge: 31,
      lore: { backstory: 'Evidence-backed career story.' },
      rivalries: [{ rivalName: 'Willie Mays', confidence: 90 }],
      confidence: { overall: 94, fields: { power: { confidence: 95 } } },
      personalityEvidence: [],
      researchFlags: [],
      identityClaims: [{ id: '1', evidenceBacked: true }],
      provenance: { flags: [] },
    },
  };
}

function payload(players: HistoricalLegendAppPlayer[]): HistoricalLegendsAppPayload {
  const profileCounts = { Career: 0, Peak: 0, 'Draft Pool': 0 };
  for (const player of players) profileCounts[player.historicalProfileType] += 1;
  return {
    schemaVersion: 'historical-legends-app-v1',
    sourceEditionId: 'test-edition',
    sourceContentHash: 'test-content',
    sourceSha256: SOURCE_SHA,
    generatedAt: '2026-07-14T00:00:00.000Z',
    playerCount: new Set(players.map((player) => player.historicalLegend.playerId)).size,
    profileCount: players.length,
    profileCounts,
    players,
  };
}

function stockPlayer(): Player {
  return {
    ...card('Draft Pool', 'draft'),
    id: 'stock-player',
    sourceDatabase: 'SMB4',
    sourceId: undefined,
    historicalSourceId: undefined,
    versionGroupId: undefined,
    historicalProfileType: undefined,
    historicalLegend: undefined,
  };
}

describe('Historical Legends app import', () => {
  beforeEach(async () => clearAllLeagueBuilderData());
  afterEach(() => __resetLeagueBuilderDatabaseForTests());

  test('rejects an unpinned or mismatched source before writing', () => {
    const data = payload([card('Career', 'career')]);
    expect(() => validateHistoricalLegendsPayload(data, null)).toThrow(/not pinned/i);
    expect(() => validateHistoricalLegendsPayload(data, 'b'.repeat(64))).toThrow(/mismatch/i);
  });

  test('rejects modified generated bytes even when embedded source provenance is unchanged', async () => {
    const data = payload([card('Career', 'career')]);
    const original = JSON.stringify(data);
    const pinnedAssetDigest = await digest(original);
    const verified = await parseHistoricalLegendsPayloadBytes(
      new TextEncoder().encode(original),
      pinnedAssetDigest,
    );
    expect(verified.sourceSha256).toBe(SOURCE_SHA);

    const modified = original.replace('"power":92', '"power":91');
    expect(JSON.parse(modified).sourceSha256).toBe(SOURCE_SHA);
    await expect(parseHistoricalLegendsPayloadBytes(
      new TextEncoder().encode(modified),
      pinnedAssetDigest,
    )).rejects.toThrow(/app-asset SHA-256 mismatch/i);
  });

  test('imports cards idempotently while preserving lore, rivalries, confidence, and non-Legends players', async () => {
    await savePlayer(stockPlayer());
    const data = payload([
      card('Career', 'career'),
      card('Peak', 'peak'),
      card('Draft Pool', 'draft'),
    ]);

    const first = await importHistoricalLegendsPayload(data, SOURCE_SHA);
    const second = await importHistoricalLegendsPayload(data, SOURCE_SHA);
    const players = await getAllPlayers();
    const legends = players.filter((player) => player.sourceDatabase === 'HISTORICAL_LEGENDS');

    expect(first).toMatchObject({ players: 3, playerGroups: 1, removedStaleCards: 0 });
    expect(second).toMatchObject({ players: 3, playerGroups: 1, removedStaleCards: 0 });
    expect(players).toHaveLength(4);
    expect(legends).toHaveLength(3);
    expect(new Set(legends.map((player) => player.id))).toEqual(new Set([
      'hl:aaroh101:career',
      'hl:aaroh101:peak',
      'hl:aaroh101:draft',
    ]));
    expect(legends[0].historicalLegend).toMatchObject({
      lore: { backstory: 'Evidence-backed career story.' },
      rivalries: [{ rivalName: 'Willie Mays', confidence: 90 }],
      confidence: { overall: 94 },
    });
    expect(players.some((player) => player.id === 'stock-player')).toBe(true);
  });

  test('removes only stale Historical Legends cards on refresh', async () => {
    const career = card('Career', 'career');
    const peak = card('Peak', 'peak');
    await importHistoricalLegendsPayload(payload([career, peak]), SOURCE_SHA);

    const refreshed = await importHistoricalLegendsPayload(payload([career]), SOURCE_SHA);
    const players = await getAllPlayers();
    expect(refreshed.removedStaleCards).toBe(1);
    expect(players.map((player) => player.id)).toEqual(['hl:aaroh101:career']);
  });

  test('preserves matching Legends league assignments on reimport', async () => {
    const career = card('Career', 'career');
    const assignment = { leagueId: 'legends-league', teamId: 'yankees', rosterStatus: 'MLB' as const };
    await savePlayer({ ...career, leagueAssignments: [assignment] });

    await importHistoricalLegendsPayload(payload([career]), SOURCE_SHA);

    expect((await getAllPlayers())[0].leagueAssignments).toEqual([assignment]);
  });

  test('refuses every assigned stale Legends card before changing players or team rosters', async () => {
    const stale = {
      ...card('Career', 'career'),
      id: 'hl:aaroh101:legacy-career',
      leagueAssignments: [{ leagueId: 'legends-league', teamId: 'yankees', rosterStatus: 'MLB' as const }],
    };
    await savePlayer(stale);
    await saveTeamRoster({
      ...createEmptyTeamRoster('yankees'),
      mlbRoster: [stale.id],
    });
    const rosterBefore = await getTeamRoster('yankees');

    await expect(importHistoricalLegendsPayload(
      payload([card('Peak', 'peak')]),
      SOURCE_SHA,
    )).rejects.toThrow(/assigned stale.*cannot be removed by reimport/i);

    const players = await getAllPlayers();
    expect(players.map((player) => player.id)).toEqual(['hl:aaroh101:legacy-career']);
    expect(await getTeamRoster('yankees')).toEqual(rosterBefore);
  });

  test('preflights incoming card ids and never overwrites a non-Legends owner', async () => {
    const incoming = card('Career', 'career');
    const collision = { ...stockPlayer(), id: incoming.id };
    await savePlayer(collision);

    await expect(importHistoricalLegendsPayload(payload([incoming]), SOURCE_SHA)).rejects.toThrow(
      /already owned by non-Legends source SMB4/i,
    );

    const players = await getAllPlayers();
    expect(players).toHaveLength(1);
    expect(players[0]).toMatchObject({ id: incoming.id, sourceDatabase: 'SMB4' });
  });
});
