import { chromium } from 'playwright';
const dir = '/Users/johnkruse/Projects/kbl-tracker--auction-ux/spec-docs/prototypes/franchise-lens/';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1180,height:1000}, deviceScaleFactor:2 });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://localhost:4188/__preview/franchise-lens',{waitUntil:'networkidle',timeout:20000});
await p.waitForTimeout(900);
await p.screenshot({ path: dir+'react-home-tox.png', fullPage:true });
await p.evaluate(()=>{const t=[...document.querySelectorAll('.fen-tab')].find(x=>x.textContent.trim()==='Roster'); if(t)t.click();});
await p.waitForTimeout(350);
await p.screenshot({ path: dir+'react-roster-tox.png', fullPage:true });
console.log('ERRORS='+JSON.stringify(errs)); await b.close(); console.log('DONE');
