import { chromium } from 'playwright';
const dir = '/Users/johnkruse/Projects/kbl-tracker--auction-ux/spec-docs/prototypes/draft-and-checkpoint/';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1180, height: 960 }, deviceScaleFactor: 2 });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('file://' + dir + 'index.html', { waitUntil:'networkidle', timeout:15000 }).catch(()=>{});
await p.waitForTimeout(1100);
await p.screenshot({ path: dir + 'draft-checkpoint-full.png', fullPage: true });
const boards = await p.$$('.board');
await boards[0].screenshot({ path: dir + 'draft.png' });
await boards[1].screenshot({ path: dir + 'checkpoint.png' });
console.log('ERRORS='+JSON.stringify(errs)); await b.close(); console.log('DONE');
