/**
 * tierParams.ts — T3 empirical tier parameters (DATA ONLY, generated).
 *
 * Generated by scripts/analyze-pool.py from:
 *   - src/data/playerDatabase.ts (440-player stock SMB4 pool = Juiced, spec D3)
 *   - src/data/ivCurves.ts + src/data/traitPricing.ts (T1, authoritative)
 *   - spec-docs/reference/Team_Builder_Archetype_Logic_Template.xlsx ('Luxury Cap' A:F + AT:BE)
 * DO NOT EDIT BY HAND - rerun the script. Deterministic: identical output every run.
 *
 * Derivations (full work shown in spec-docs/T3_POOL_ANALYSIS.md):
 *   - tier scales: grade-ladder method (§5.1) - median IV per SMB4 letter grade,
 *     piecewise-linear ladder; scale = ladder(meanOrdinal - steps) / ladder(meanOrdinal).
 *     Multiplicative transform: tierIV = juiced kblIV x scale.
 *   - V117 kblIV usage layer (§3.9): rawIV remains workbook-exact for anchors; pool
 *     analysis uses pitcher batting repriced on hitter curves with role usage weights.
 *   - tierCap = max(maxPoolIV / starBudgetShare, 22 x medianPoolIV x rosterHeadroom) (§5.2)
 *   - luxury caps: 65th percentile (luxuryCapPercentile) of the STOCK-TEAM top-N sum
 *     distribution - the 20 real SMB4 rosters' observed concentrations (§5.3; the
 *     ignore-budget contention ladder was derived too and REJECTED: caps so high the
 *     tax layer never binds - see T3_POOL_ANALYSIS.md §R4).
 *   - penalty $ scale sigma = pool median IV / XBL workbook anchor median salary;
 *     workbook curve shapes port unchanged except the approved quadratic pitcher
 *     rotation/bullpen POW/CON override (JK ruling 2026-07-15).
 *   - modification deltas: stored as FRACTIONS of the XBL cap they shift (tier-invariant),
 *     plus per-tier absolute tables (fraction x tier cap) (§5.3, §6.2).
 *   - farm nerf: one grade step left of the league tier (§7.4); no new free parameter.
 */

export type TierKey = 'juiced' | 'standard' | 'nerfed';

export interface TierShiftParams {
  scale: number;            // multiplicative IV-space transform vs the observed (Juiced) pool
  gradeStepsLeft: number;   // §5.1 definition of the tier
  impliedMeanIV: number;    // observed pool mean x scale
}

export const TIER_SHIFTS: Record<TierKey, TierShiftParams> = {
  juiced: { scale: 1.000000, gradeStepsLeft: 0, impliedMeanIV: 54854 },
  standard: { scale: 0.882696, gradeStepsLeft: 1, impliedMeanIV: 48420 },
  nerfed: { scale: 0.791877, gradeStepsLeft: 2, impliedMeanIV: 43438 },
};

/** First-order uniform rating multiplier that reproduces each tier's IV scale through
 *  the attribute curves on this pool (bisection-solved; Player Generator convenience). */
export const TIER_RATING_SCALES: Record<TierKey, number> = {
  juiced: 1.000000,
  standard: 0.954274,
  nerfed: 0.914213,
};

/** §7.4 farm-draft nerf: farm pool IV scale RELATIVE TO its league tier (one grade step). */
export const FARM_NERF_SCALES: Record<TierKey, number> = {
  juiced: 0.882696,
  standard: 0.897111,
  nerfed: 0.875197,
};

export interface TierCapParams {
  tierCap: number;
  starBranch: number;       // maxPoolIV / starBudgetShare(0.33)
  rosterBranch: number;     // 22 x medianPoolIV x rosterHeadroom(1.15)
  maxPoolIV: number;
  medianPoolIV: number;
}

export const TIER_CAPS: Record<TierKey, TierCapParams> = {
  juiced: { tierCap: 1205836, starBranch: 660976, rosterBranch: 1205836, maxPoolIV: 218122, medianPoolIV: 47662 },
  standard: { tierCap: 1064387, starBranch: 583441, rosterBranch: 1064387, maxPoolIV: 192535, medianPoolIV: 42071 },
  nerfed: { tierCap: 954874, starBranch: 523411, rosterBranch: 954874, maxPoolIV: 172726, medianPoolIV: 37742 },
};

export interface LuxuryCapRow {
  group: 'hitters' | 'rotation' | 'bullpen';
  stat: 'POW' | 'CON' | 'SPD' | 'FLD' | 'ARM' | 'VEL' | 'JNK' | 'ACC';
  topN: number;
  cap: number;              // tier-scaled neutral cap (rating-sum)
  penaltyCurve: number;     // response shape; approved KBL tuning may supersede the XBL source curve
  penaltyPer100: number;    // $ per (overage/100)^curve - sigma-scaled to this pool
  minAdder: number;         // flat $ when over - sigma-scaled
  ratingBasis?: 'pitcher-role-usage-v1'; // absent means legacy raw pitcher-secondary ratings
}

/**
 * Pitcher POW/CON are useful secondary skills, but should not price like dominant pitching.
 * Use playing-time-adjusted stock-team caps and a soft quadratic ramp so modest
 * overages stay modest and only deliberate stacking becomes expensive.
 */
export const PITCHER_SECONDARY_BATTING_PENALTY_CURVE = 2;
export const LUXURY_TAX_RATING_BASIS = 'pitcher-role-usage-v1' as const;

export const LUXURY_CAP_TABLES: Record<TierKey, LuxuryCapRow[]> = {
  juiced: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 613.8, penaltyCurve: 1.5, penaltyPer100: 1645997, minAdder: 3292, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 616.0, penaltyCurve: 1.8, penaltyPer100: 1097332, minAdder: 2195, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 617.1, penaltyCurve: 1.8, penaltyPer100: 1097332, minAdder: 2195, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 612.7, penaltyCurve: 2, penaltyPer100: 768132, minAdder: 658, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 597.4, penaltyCurve: 1.8, penaltyPer100: 987598, minAdder: 988, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'POW', topN: 4, cap: 17.5, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 2194663, minAdder: 3292, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'CON', topN: 4, cap: 17.3, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1316798, minAdder: 2743, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'SPD', topN: 4, cap: 35.3, penaltyCurve: 2, penaltyPer100: 1097332, minAdder: 2743, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'FLD', topN: 4, cap: 64.8, penaltyCurve: 2, penaltyPer100: 713266, minAdder: 1097, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 272.9, penaltyCurve: 1.5, penaltyPer100: 1645997, minAdder: 2195, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 264.4, penaltyCurve: 2, penaltyPer100: 438933, minAdder: 1097, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 299.0, penaltyCurve: 1.9, penaltyPer100: 877865, minAdder: 1317, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'POW', topN: 4, cap: 6.9, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 2304396, minAdder: 5487, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'CON', topN: 4, cap: 7.0, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1426531, minAdder: 3292, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'SPD', topN: 4, cap: 22.1, penaltyCurve: 2, penaltyPer100: 1207065, minAdder: 3292, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'FLD', topN: 4, cap: 23.6, penaltyCurve: 2, penaltyPer100: 822999, minAdder: 1097, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 234.1, penaltyCurve: 1.1, penaltyPer100: 3291995, minAdder: 5487, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 235.3, penaltyCurve: 2, penaltyPer100: 548666, minAdder: 1097, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 197.8, penaltyCurve: 1.9, penaltyPer100: 1097332, minAdder: 3292, ratingBasis: LUXURY_TAX_RATING_BASIS },
  ],
  standard: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 585.7, penaltyCurve: 1.5, penaltyPer100: 1452916, minAdder: 2906, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 587.8, penaltyCurve: 1.8, penaltyPer100: 968610, minAdder: 1937, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 588.9, penaltyCurve: 1.8, penaltyPer100: 968610, minAdder: 1937, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 584.7, penaltyCurve: 2, penaltyPer100: 678027, minAdder: 581, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 570.0, penaltyCurve: 1.8, penaltyPer100: 871749, minAdder: 872, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'POW', topN: 4, cap: 16.7, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1937221, minAdder: 2906, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'CON', topN: 4, cap: 16.6, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1162333, minAdder: 2422, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'SPD', topN: 4, cap: 33.7, penaltyCurve: 2, penaltyPer100: 968610, minAdder: 2422, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'FLD', topN: 4, cap: 61.9, penaltyCurve: 2, penaltyPer100: 629597, minAdder: 969, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 260.4, penaltyCurve: 1.5, penaltyPer100: 1452916, minAdder: 1937, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 252.3, penaltyCurve: 2, penaltyPer100: 387444, minAdder: 969, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 285.3, penaltyCurve: 1.9, penaltyPer100: 774888, minAdder: 1162, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'POW', topN: 4, cap: 6.6, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 2034082, minAdder: 4843, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'CON', topN: 4, cap: 6.7, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1259194, minAdder: 2906, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'SPD', topN: 4, cap: 21.1, penaltyCurve: 2, penaltyPer100: 1065472, minAdder: 2906, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'FLD', topN: 4, cap: 22.5, penaltyCurve: 2, penaltyPer100: 726458, minAdder: 969, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 223.4, penaltyCurve: 1.1, penaltyPer100: 2905831, minAdder: 4843, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 224.6, penaltyCurve: 2, penaltyPer100: 484305, minAdder: 969, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 188.7, penaltyCurve: 1.9, penaltyPer100: 968610, minAdder: 2906, ratingBasis: LUXURY_TAX_RATING_BASIS },
  ],
  nerfed: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 561.1, penaltyCurve: 1.5, penaltyPer100: 1303427, minAdder: 2607, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 563.2, penaltyCurve: 1.8, penaltyPer100: 868952, minAdder: 1738, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 564.2, penaltyCurve: 1.8, penaltyPer100: 868952, minAdder: 1738, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 560.1, penaltyCurve: 2, penaltyPer100: 608266, minAdder: 521, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 546.1, penaltyCurve: 1.8, penaltyPer100: 782056, minAdder: 782, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'POW', topN: 4, cap: 16.0, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1737903, minAdder: 2607, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'CON', topN: 4, cap: 15.9, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1042742, minAdder: 2172, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'SPD', topN: 4, cap: 32.3, penaltyCurve: 2, penaltyPer100: 868952, minAdder: 2172, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'FLD', topN: 4, cap: 59.3, penaltyCurve: 2, penaltyPer100: 564818, minAdder: 869, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 249.5, penaltyCurve: 1.5, penaltyPer100: 1303427, minAdder: 1738, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 241.7, penaltyCurve: 2, penaltyPer100: 347581, minAdder: 869, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 273.3, penaltyCurve: 1.9, penaltyPer100: 695161, minAdder: 1043, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'POW', topN: 4, cap: 6.3, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1824798, minAdder: 4345, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'CON', topN: 4, cap: 6.4, penaltyCurve: PITCHER_SECONDARY_BATTING_PENALTY_CURVE, penaltyPer100: 1129637, minAdder: 2607, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'SPD', topN: 4, cap: 20.2, penaltyCurve: 2, penaltyPer100: 955847, minAdder: 2607, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'FLD', topN: 4, cap: 21.6, penaltyCurve: 2, penaltyPer100: 651714, minAdder: 869, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 214.0, penaltyCurve: 1.1, penaltyPer100: 2606855, minAdder: 4345, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 215.2, penaltyCurve: 2, penaltyPer100: 434476, minAdder: 869, ratingBasis: LUXURY_TAX_RATING_BASIS },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 180.8, penaltyCurve: 1.9, penaltyPer100: 868952, minAdder: 2607, ratingBasis: LUXURY_TAX_RATING_BASIS },
  ],
};

/** Pitcher-BATTING luxury rows (rotation/bullpen POW CON SPD FLD) are ACTIVE after DB1.
 *  The stock pool now has 179/179 pitcher batterRatings, so no v1 luxury rows are disabled.
 *  Kept as an explicit empty registry for callers that check legacy disabled rows. */
export const DISABLED_LUXURY_ROWS: Array<Omit<LuxuryCapRow, 'cap'> & { xblCap: number; disabledReason: string }> = [
];

/** §6.2 modification deltas as FRACTIONS of the XBL cap of the luxury row each shifts.
 *  Tier-invariant ('+337 FLD' == +57.6% of the FLD cap at any tier). Apply as:
 *  shiftedCap = cap x (1 + sum(increases) - sum(decreases)). */
export type ModStat = 'POW' | 'CON' | 'SPD' | 'FLD' | 'ARM' | 'RPOW' | 'RCON' | 'RVEL' | 'RJNK' | 'RACC' | 'PVEL' | 'PJNK' | 'PACC';

export const CAP_MODIFICATION_FRACTIONS: Record<string, Partial<Record<ModStat, number>>> = {
  '--': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'POW': { POW: 0.020000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'CON': { POW: 0.000000, CON: 0.045872, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'SPD': { POW: 0.000000, CON: 0.000000, SPD: 0.045455, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'FLD': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.222222, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'ARM': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'VEL': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.200000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.230769, PJNK: 0.000000, PACC: 0.000000 },
  'JNK': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.576923, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.666667, PACC: 0.000000 },
  'ACC': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.307692, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.424242 },
  'Arm Wrestlers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: -0.170940, ARM: 0.159292, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Big and Clumsy': { POW: 0.080000, CON: 0.000000, SPD: -0.027273, FLD: -0.452991, ARM: -0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Big D': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.239316, ARM: 0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Bionic Arms': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.088496, RVEL: 0.120000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.153846, PJNK: 0.000000, PACC: 0.000000 },
  'Bloop Hitters': { POW: -0.040000, CON: 0.091743, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Bullpen Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.123077, PJNK: 0.300000, PACC: 0.212121 },
  'Call Your Shot': {
    POW: 0.100000, CON: -0.036697, SPD: -0.036364, FLD: -0.034188, ARM: -0.035398,
    RVEL: -0.170000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RJNK: -0.065385, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RACC: -0.065385, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PVEL: -0.261538, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PJNK: -0.113333, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PACC: -0.103030, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
  },
  'Catch the Ball!': { POW: -0.020000, CON: -0.018349, SPD: -0.018182, FLD: 0.353846, ARM: 0.212389, RVEL: -0.100000, RJNK: -0.038462, RACC: -0.038462, PVEL: -0.153846, PJNK: -0.066667, PACC: -0.060606 },
  'Con-Artists': { POW: -0.040000, CON: 0.165138, SPD: -0.036364, FLD: -0.034188, ARM: -0.035398, RVEL: -0.200000, RJNK: -0.076923, RACC: -0.076923, PVEL: -0.307692, PJNK: -0.133333, PACC: -0.121212 },
  'Dart Throwers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.079646, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.153846, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.242424 },
  'Defense Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.027273, FLD: 0.153846, ARM: 0.070796, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Defense First': {
    POW: -0.120000, CON: -0.110092, SPD: 0.200000, FLD: 0.576068, ARM: 0.265487,
    RVEL: -0.340000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RJNK: -0.196154, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RACC: -0.147115, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PVEL: -0.392307, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PJNK: -0.340000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PACC: -0.206060, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
  },
  'Do You Even Lift?': { POW: 0.010000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.061947, RVEL: 0.080000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.076923, PJNK: 0.000000, PACC: 0.000000 },
  'Fence Swingers': { POW: 0.040000, CON: -0.055046, SPD: -0.036364, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Fireballers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.500000, RJNK: 0.000000, RACC: -0.461538, PVEL: 0.461538, PJNK: 0.000000, PACC: -0.545455 },
  'Flash Leather': { POW: 0.000000, CON: 0.000000, SPD: 0.045455, FLD: 0.205128, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Fundamentals': { POW: 0.000000, CON: 0.018349, SPD: 0.000000, FLD: 0.102564, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.076923, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.060606 },
  'Great Bambino': { POW: 0.060000, CON: 0.000000, SPD: -0.181818, FLD: 0.000000, ARM: 0.000000, RVEL: 0.150000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.153846, PJNK: 0.000000, PACC: 0.000000 },
  'Junk Ballers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.307692, RACC: 0.192308, PVEL: 0.000000, PJNK: 0.533333, PACC: 0.242424 },
  'Lazer Guns': {
    POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000,
    RVEL: 0.153000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RJNK: -0.850000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RACC: 0.163462, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PVEL: 0.156923, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PJNK: -0.850000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PACC: 0.206060, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
  },
  'Offense Boost': { POW: 0.010000, CON: 0.014679, SPD: 0.027273, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Pine Tar': { POW: 0.010000, CON: 0.018349, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.076923, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.060606 },
  'Pinpoint Pitchers': { POW: -0.024000, CON: -0.022018, SPD: -0.021818, FLD: -0.020513, ARM: -0.021239, RVEL: -0.120000, RJNK: -0.046154, RACC: 0.461538, PVEL: -0.184615, PJNK: -0.080000, PACC: 0.545455 },
  'Rotation Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.200000, RJNK: 0.192308, RACC: 0.173077, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Run Like the Wind': { POW: -0.020000, CON: -0.045872, SPD: 0.118182, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  "Run n' Gun": { POW: 0.000000, CON: 0.000000, SPD: 0.036364, FLD: -0.136752, ARM: 0.106195, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Slap Hitters': { POW: -0.020000, CON: 0.045872, SPD: 0.032727, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Small Ballers': { POW: 0.000000, CON: 0.022018, SPD: 0.021818, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Torpedo Bats': { POW: 0.016000, CON: 0.018349, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Track Stars': {
    POW: -0.040000, CON: -0.036697, SPD: 0.181818, FLD: -0.034188, ARM: -0.035398,
    RVEL: -0.170000, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RJNK: -0.065385, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    RACC: -0.065385, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PVEL: -0.261538, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PJNK: -0.113333, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
    PACC: -0.103030, // CONTRACT_TAXSWING_2026-07-10 Amendment 1: pitching fraction scaled by 0.85.
  },
  'Warning Track': { POW: -0.160000, CON: 0.100917, SPD: 0.127273, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'We Got Gas': { POW: -0.050000, CON: -0.045872, SPD: -0.045455, FLD: -0.042735, ARM: -0.044248, RVEL: 0.600000, RJNK: -0.096154, RACC: -0.096154, PVEL: 0.492308, PJNK: -0.166667, PACC: -0.151515 },
  'Well Rounded': { POW: 0.010000, CON: 0.009174, SPD: 0.009091, FLD: 0.008547, ARM: 0.008850, RVEL: 0.050000, RJNK: 0.019231, RACC: 0.019231, PVEL: 0.076923, PJNK: 0.033333, PACC: 0.030303 },
};

export const T3_DERIVATION_INPUTS = {
  poolSize: 440,
  poolMeanIV: 54854,
  poolMeanGradeOrdinal: 5.7455,  // ladder D=0 .. S=11
  luxuryCapPercentile: 0.65,
  starBudgetShare: 0.33,
  rosterHeadroom: 1.15,
  penaltySigmaJuiced: 1.097332,  // pool median IV / XBL anchor median salary
  contentionLadderTeams: 20,
} as const;
