/**
 * tierParams.ts — T3 empirical tier parameters (DATA ONLY, generated).
 *
 * Generated by scripts/analyze-pool.py from:
 *   - src/data/playerDatabase.ts (440-player stock SMB4 pool = Juiced, spec D3)
 *   - src/data/ivCurves.ts + src/data/traitPricing.ts (T1, authoritative)
 *   - spec-docs/reference/Team_Builder_Archetype_Logic_Template.xlsx ('Luxury Cap' A:F + AT:BE)
 * DO NOT EDIT BY HAND - rerun the script. Deterministic: identical output every run.
 *
 * Derivations (full work shown in spec-docs/T3_POOL_ANALYSIS.md):
 *   - tier scales: grade-ladder method (§5.1) - median IV per SMB4 letter grade,
 *     piecewise-linear ladder; scale = ladder(meanOrdinal - steps) / ladder(meanOrdinal).
 *     Multiplicative transform: tierIV = juicedIV x scale.
 *   - tierCap = max(maxPoolIV / starBudgetShare, 22 x medianPoolIV x rosterHeadroom) (§5.2)
 *   - luxury caps: 65th percentile (luxuryCapPercentile) of the STOCK-TEAM top-N sum
 *     distribution - the 20 real SMB4 rosters' observed concentrations (§5.3; the
 *     ignore-budget contention ladder was derived too and REJECTED: caps so high the
 *     tax layer never binds - see T3_POOL_ANALYSIS.md §R4).
 *   - penalty $ scale sigma = pool median IV / XBL workbook anchor median salary;
 *     penalty curve exponents port unchanged (D13 'ratios and shapes').
 *   - modification deltas: stored as FRACTIONS of the XBL cap they shift (tier-invariant),
 *     plus per-tier absolute tables (fraction x tier cap) (§5.3, §6.2).
 *   - farm nerf: one grade step left of the league tier (§7.4); no new free parameter.
 */

export type TierKey = 'juiced' | 'standard' | 'nerfed';

export interface TierShiftParams {
  scale: number;            // multiplicative IV-space transform vs the observed (Juiced) pool
  gradeStepsLeft: number;   // §5.1 definition of the tier
  impliedMeanIV: number;    // observed pool mean x scale
}

export const TIER_SHIFTS: Record<TierKey, TierShiftParams> = {
  juiced: { scale: 1.000000, gradeStepsLeft: 0, impliedMeanIV: 60225 },
  standard: { scale: 0.784163, gradeStepsLeft: 1, impliedMeanIV: 47226 },
  nerfed: { scale: 0.679864, gradeStepsLeft: 2, impliedMeanIV: 40945 },
};

/** First-order uniform rating multiplier that reproduces each tier's IV scale through
 *  the attribute curves on this pool (bisection-solved; Player Generator convenience). */
export const TIER_RATING_SCALES: Record<TierKey, number> = {
  juiced: 1.000000,
  standard: 0.913779,
  nerfed: 0.862636,
};

/** §7.4 farm-draft nerf: farm pool IV scale RELATIVE TO its league tier (one grade step). */
export const FARM_NERF_SCALES: Record<TierKey, number> = {
  juiced: 0.784163,
  standard: 0.866993,
  nerfed: 0.915129,
};

export interface TierCapParams {
  tierCap: number;
  starBranch: number;       // maxPoolIV / starBudgetShare(0.33)
  rosterBranch: number;     // 22 x medianPoolIV x rosterHeadroom(1.15)
  maxPoolIV: number;
  medianPoolIV: number;
}

export const TIER_CAPS: Record<TierKey, TierCapParams> = {
  juiced: { tierCap: 1251237, starBranch: 1218382, rosterBranch: 1251237, maxPoolIV: 402066, medianPoolIV: 49456 },
  standard: { tierCap: 981174, starBranch: 955411, rosterBranch: 981174, maxPoolIV: 315285, medianPoolIV: 38782 },
  nerfed: { tierCap: 850671, starBranch: 828334, rosterBranch: 850671, maxPoolIV: 273350, medianPoolIV: 33623 },
};

export interface LuxuryCapRow {
  group: 'hitters' | 'rotation' | 'bullpen';
  stat: 'POW' | 'CON' | 'SPD' | 'FLD' | 'ARM' | 'VEL' | 'JNK' | 'ACC';
  topN: number;
  cap: number;              // tier-scaled neutral cap (rating-sum)
  penaltyCurve: number;     // XBL shape, ports unchanged
  penaltyPer100: number;    // $ per (overage/100)^curve - sigma-scaled to this pool
  minAdder: number;         // flat $ when over - sigma-scaled
}

export const LUXURY_CAP_TABLES: Record<TierKey, LuxuryCapRow[]> = {
  juiced: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 609.4, penaltyCurve: 1.5, penaltyPer100: 1707971, minAdder: 3416 },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 624.5, penaltyCurve: 1.8, penaltyPer100: 1138647, minAdder: 2277 },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 583.8, penaltyCurve: 1.8, penaltyPer100: 1138647, minAdder: 2277 },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 626.4, penaltyCurve: 2, penaltyPer100: 797053, minAdder: 683 },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 593.8, penaltyCurve: 1.8, penaltyPer100: 1024782, minAdder: 1025 },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 261.0, penaltyCurve: 1.5, penaltyPer100: 1707971, minAdder: 2277 },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 239.1, penaltyCurve: 2, penaltyPer100: 455459, minAdder: 1139 },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 293.9, penaltyCurve: 1.9, penaltyPer100: 910918, minAdder: 1366 },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 228.5, penaltyCurve: 1.1, penaltyPer100: 3415941, minAdder: 5693 },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 231.1, penaltyCurve: 2, penaltyPer100: 569324, minAdder: 1139 },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 195.7, penaltyCurve: 1.9, penaltyPer100: 1138647, minAdder: 3416 },
  ],
  standard: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 556.8, penaltyCurve: 1.5, penaltyPer100: 1339328, minAdder: 2679 },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 570.7, penaltyCurve: 1.8, penaltyPer100: 892886, minAdder: 1786 },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 533.5, penaltyCurve: 1.8, penaltyPer100: 892886, minAdder: 1786 },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 572.4, penaltyCurve: 2, penaltyPer100: 625020, minAdder: 536 },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 542.6, penaltyCurve: 1.8, penaltyPer100: 803597, minAdder: 804 },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 238.5, penaltyCurve: 1.5, penaltyPer100: 1339328, minAdder: 1786 },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 218.4, penaltyCurve: 2, penaltyPer100: 357154, minAdder: 893 },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 268.5, penaltyCurve: 1.9, penaltyPer100: 714308, minAdder: 1071 },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 208.8, penaltyCurve: 1.1, penaltyPer100: 2678657, minAdder: 4464 },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 211.2, penaltyCurve: 2, penaltyPer100: 446443, minAdder: 893 },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 178.8, penaltyCurve: 1.9, penaltyPer100: 892886, minAdder: 2679 },
  ],
  nerfed: [
    { group: 'hitters', stat: 'POW', topN: 8, cap: 525.6, penaltyCurve: 1.5, penaltyPer100: 1161188, minAdder: 2322 },
    { group: 'hitters', stat: 'CON', topN: 8, cap: 538.8, penaltyCurve: 1.8, penaltyPer100: 774126, minAdder: 1548 },
    { group: 'hitters', stat: 'SPD', topN: 8, cap: 503.6, penaltyCurve: 1.8, penaltyPer100: 774126, minAdder: 1548 },
    { group: 'hitters', stat: 'FLD', topN: 8, cap: 540.4, penaltyCurve: 2, penaltyPer100: 541888, minAdder: 464 },
    { group: 'hitters', stat: 'ARM', topN: 8, cap: 512.2, penaltyCurve: 1.8, penaltyPer100: 696713, minAdder: 697 },
    { group: 'rotation', stat: 'VEL', topN: 4, cap: 225.1, penaltyCurve: 1.5, penaltyPer100: 1161188, minAdder: 1548 },
    { group: 'rotation', stat: 'JNK', topN: 4, cap: 206.2, penaltyCurve: 2, penaltyPer100: 309650, minAdder: 774 },
    { group: 'rotation', stat: 'ACC', topN: 4, cap: 253.5, penaltyCurve: 1.9, penaltyPer100: 619300, minAdder: 929 },
    { group: 'bullpen', stat: 'VEL', topN: 3, cap: 197.1, penaltyCurve: 1.1, penaltyPer100: 2322377, minAdder: 3871 },
    { group: 'bullpen', stat: 'JNK', topN: 3, cap: 199.4, penaltyCurve: 2, penaltyPer100: 387063, minAdder: 774 },
    { group: 'bullpen', stat: 'ACC', topN: 3, cap: 168.8, penaltyCurve: 1.9, penaltyPer100: 774126, minAdder: 2322 },
  ],
};

/** Pitcher-BATTING luxury rows (rotation/bullpen POW CON SPD FLD): DISABLED for v1.
 *  89/178 stock pitchers carry no batterRatings, so stock-team top-N sums for these
 *  stats are corrupted toward 0 and 65th-pct caps would megatax any pitcher that HAS
 *  batting data. XBL penalty shapes preserved verbatim below (caps in XBL rating units,
 *  $ unscaled) - re-derive via scripts/analyze-pool.py after the DB gap is filled. */
export const DISABLED_LUXURY_ROWS: Array<Omit<LuxuryCapRow, 'cap'> & { xblCap: number; disabledReason: string }> = [
  { group: 'rotation', stat: 'POW', topN: 4, xblCap: 120, penaltyCurve: 1, penaltyPer100: 2000000, minAdder: 3000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'rotation', stat: 'CON', topN: 4, xblCap: 160, penaltyCurve: 1, penaltyPer100: 1200000, minAdder: 2500, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'rotation', stat: 'SPD', topN: 4, xblCap: 300, penaltyCurve: 2, penaltyPer100: 1000000, minAdder: 2500, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'rotation', stat: 'FLD', topN: 4, xblCap: 396, penaltyCurve: 2, penaltyPer100: 650000, minAdder: 1000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'bullpen', stat: 'POW', topN: 4, xblCap: 120, penaltyCurve: 1, penaltyPer100: 2100000, minAdder: 5000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'bullpen', stat: 'CON', topN: 4, xblCap: 120, penaltyCurve: 1, penaltyPer100: 1300000, minAdder: 3000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'bullpen', stat: 'SPD', topN: 4, xblCap: 260, penaltyCurve: 2, penaltyPer100: 1100000, minAdder: 3000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
  { group: 'bullpen', stat: 'FLD', topN: 4, xblCap: 396, penaltyCurve: 2, penaltyPer100: 750000, minAdder: 1000, disabledReason: 'pitcher batterRatings data gap (89/178)' },
];

/** §6.2 modification deltas as FRACTIONS of the XBL cap of the luxury row each shifts.
 *  Tier-invariant ('+337 FLD' == +57.6% of the FLD cap at any tier). Apply as:
 *  shiftedCap = cap x (1 + sum(increases) - sum(decreases)). */
export type ModStat = 'POW' | 'CON' | 'SPD' | 'FLD' | 'ARM' | 'RVEL' | 'RJNK' | 'RACC' | 'PVEL' | 'PJNK' | 'PACC';

export const CAP_MODIFICATION_FRACTIONS: Record<string, Record<ModStat, number>> = {
  '--': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'POW': { POW: 0.020000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'CON': { POW: 0.000000, CON: 0.045872, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'SPD': { POW: 0.000000, CON: 0.000000, SPD: 0.045455, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'FLD': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.222222, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'ARM': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'VEL': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.200000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.230769, PJNK: 0.000000, PACC: 0.000000 },
  'JNK': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.576923, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.666667, PACC: 0.000000 },
  'ACC': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.307692, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.424242 },
  'Arm Wrestlers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: -0.170940, ARM: 0.159292, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Big and Clumsy': { POW: 0.080000, CON: 0.000000, SPD: -0.027273, FLD: -0.452991, ARM: -0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Big D': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.239316, ARM: 0.088496, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Bionic Arms': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.088496, RVEL: 0.120000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.153846, PJNK: 0.000000, PACC: 0.000000 },
  'Bloop Hitters': { POW: -0.040000, CON: 0.091743, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Bullpen Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.123077, PJNK: 0.300000, PACC: 0.212121 },
  'Call Your Shot': { POW: 0.100000, CON: -0.036697, SPD: -0.036364, FLD: -0.034188, ARM: -0.035398, RVEL: -0.200000, RJNK: -0.076923, RACC: -0.076923, PVEL: -0.307692, PJNK: -0.133333, PACC: -0.121212 },
  'Catch the Ball!': { POW: -0.020000, CON: -0.018349, SPD: -0.018182, FLD: 0.353846, ARM: 0.212389, RVEL: -0.100000, RJNK: -0.038462, RACC: -0.038462, PVEL: -0.153846, PJNK: -0.066667, PACC: -0.060606 },
  'Con-Artists': { POW: -0.040000, CON: 0.165138, SPD: -0.036364, FLD: -0.034188, ARM: -0.035398, RVEL: -0.200000, RJNK: -0.076923, RACC: -0.076923, PVEL: -0.307692, PJNK: -0.133333, PACC: -0.121212 },
  'Dart Throwers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.079646, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.153846, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.242424 },
  'Defense Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.027273, FLD: 0.153846, ARM: 0.070796, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Defense First': { POW: -0.120000, CON: -0.110092, SPD: 0.200000, FLD: 0.576068, ARM: 0.265487, RVEL: -0.400000, RJNK: -0.230769, RACC: -0.173077, PVEL: -0.461538, PJNK: -0.400000, PACC: -0.242424 },
  'Do You Even Lift?': { POW: 0.010000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.061947, RVEL: 0.080000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.076923, PJNK: 0.000000, PACC: 0.000000 },
  'Fence Swingers': { POW: 0.040000, CON: -0.055046, SPD: -0.036364, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Fireballers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.500000, RJNK: 0.000000, RACC: -0.461538, PVEL: 0.461538, PJNK: 0.000000, PACC: -0.545455 },
  'Flash Leather': { POW: 0.000000, CON: 0.000000, SPD: 0.045455, FLD: 0.205128, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Fundamentals': { POW: 0.000000, CON: 0.018349, SPD: 0.000000, FLD: 0.102564, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.076923, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.060606 },
  'Great Bambino': { POW: 0.060000, CON: 0.000000, SPD: -0.181818, FLD: 0.000000, ARM: 0.000000, RVEL: 0.150000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.153846, PJNK: 0.000000, PACC: 0.000000 },
  'Junk Ballers': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.307692, RACC: 0.192308, PVEL: 0.000000, PJNK: 0.533333, PACC: 0.242424 },
  'Lazer Guns': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.180000, RJNK: -1.000000, RACC: 0.192308, PVEL: 0.184615, PJNK: -1.000000, PACC: 0.242424 },
  'Offense Boost': { POW: 0.010000, CON: 0.014679, SPD: 0.027273, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Pine Tar': { POW: 0.010000, CON: 0.018349, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.076923, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.060606 },
  'Pinpoint Pitchers': { POW: -0.024000, CON: -0.022018, SPD: -0.021818, FLD: -0.020513, ARM: -0.021239, RVEL: -0.120000, RJNK: -0.046154, RACC: 0.461538, PVEL: -0.184615, PJNK: -0.080000, PACC: 0.545455 },
  'Rotation Boost': { POW: 0.000000, CON: 0.000000, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.200000, RJNK: 0.192308, RACC: 0.173077, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Run Like the Wind': { POW: -0.020000, CON: -0.045872, SPD: 0.118182, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  "Run n' Gun": { POW: 0.000000, CON: 0.000000, SPD: 0.036364, FLD: -0.136752, ARM: 0.106195, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Slap Hitters': { POW: -0.020000, CON: 0.045872, SPD: 0.032727, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Small Ballers': { POW: 0.000000, CON: 0.022018, SPD: 0.021818, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Torpedo Bats': { POW: 0.016000, CON: 0.018349, SPD: 0.000000, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'Track Stars': { POW: -0.040000, CON: -0.036697, SPD: 0.181818, FLD: -0.034188, ARM: -0.035398, RVEL: -0.200000, RJNK: -0.076923, RACC: -0.076923, PVEL: -0.307692, PJNK: -0.133333, PACC: -0.121212 },
  'Warning Track': { POW: -0.160000, CON: 0.100917, SPD: 0.127273, FLD: 0.000000, ARM: 0.000000, RVEL: 0.000000, RJNK: 0.000000, RACC: 0.000000, PVEL: 0.000000, PJNK: 0.000000, PACC: 0.000000 },
  'We Got Gas': { POW: -0.050000, CON: -0.045872, SPD: -0.045455, FLD: -0.042735, ARM: -0.044248, RVEL: 0.600000, RJNK: -0.096154, RACC: -0.096154, PVEL: 0.492308, PJNK: -0.166667, PACC: -0.151515 },
  'Well Rounded': { POW: 0.010000, CON: 0.009174, SPD: 0.009091, FLD: 0.008547, ARM: 0.008850, RVEL: 0.050000, RJNK: 0.019231, RACC: 0.019231, PVEL: 0.076923, PJNK: 0.033333, PACC: 0.030303 },
};

export const T3_DERIVATION_INPUTS = {
  poolSize: 440,
  poolMeanIV: 60225,
  poolMeanGradeOrdinal: 5.7705,  // ladder D=0 .. S=11
  luxuryCapPercentile: 0.65,
  starBudgetShare: 0.33,
  rosterHeadroom: 1.15,
  penaltySigmaJuiced: 1.138647,  // pool median IV / XBL anchor median salary
  contentionLadderTeams: 20,
} as const;
